# Generated by Django 5.2.7 on 2025-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('old_hostname', models.CharField(max_length=100)),
                ('new_hostname', models.CharField(max_length=100)),
                ('old_serial_number', models.CharField(max_length=100)),
                ('new_serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Rescheduled', 'Rescheduled')], max_length=20)),
                ('date_if_rescheduled', models.DateField(blank=True, null=True)),
                ('format_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20)),
                ('reason_not_formatted', models.TextField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20)),
                ('reason_not_uploaded', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
