# Generated by Django 5.1.2 on 2025-10-13 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0003_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Tag Refresh', 'Tag Refresh'), ('Asset Refresh', 'Asset Refresh'), ('Tech Refresh', 'Tech Refresh')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('old_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('new_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('old_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('new_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('old_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('new_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('new_mac', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechRefreshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('old_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('new_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
