# Generated by Django 5.2.7 on 2025-10-15 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0004_request_techrefreshrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Faulty', 'Faulty'), ('In Use', 'In Use'), ('Returned', 'Returned'), ('Damaged', 'Damaged')], max_length=50),
        ),
    ]
