# Generated by Django 5.2.7 on 2025-10-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='format_status',
            field=models.CharField(blank=True, choices=[('Formatted', 'Formatted'), ('Not Formatted', 'Not Formatted')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='new_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='old_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='reason_not_formatted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='reason_not_uploaded',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rescheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='upload_status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Not Yet', 'Not Yet')], default='Not Yet', max_length=20),
        ),
    ]
