# Generated by Django 5.0.7 on 2025-10-27 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0007_request_format_status_request_new_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='techrefresh',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='techrefresh',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_approver',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approver_requests',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='request',
            name='new_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='old_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techrefresh',
            name='format_status',
            field=models.CharField(
                choices=[('Completed', 'Completed'), ('Pending', 'Pending')],
                default='Pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='techrefresh',
            name='status',
            field=models.CharField(
                choices=[
                    ('Completed', 'Completed'),
                    ('Pending', 'Pending'),
                    ('Rescheduled', 'Rescheduled'),
                ],
                default='Pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='techrefresh',
            name='upload_status',
            field=models.CharField(
                choices=[('Completed', 'Completed'), ('Pending', 'Pending')],
                default='Pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='techrefreshrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Approved', 'Approved'),
                    ('Rejected', 'Rejected'),
                    ('Completed', 'Completed'),
                ],
                default='Pending',
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[
                        ('Assigned', 'Assigned'),
                        ('In Progress', 'In Progress'),
                        ('Completed', 'Completed'),
                        ('Overdue', 'Overdue'),
                    ],
                    default='Assigned',
                    max_length=50,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='related_tasks',
                    to='inventorySystem.request',
                )),
            ],
        ),
    ]
