# Generated by Django 5.0.7 on 2025-10-27 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0008_remove_inventory_last_updated_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('Asset Refresh', 'Asset Refresh'), ('Parts Upgrade', 'Parts Upgrade'), ('Tech Refresh', 'Tech Refresh')], max_length=50),
        ),
        migrations.AlterField(
            model_name='techrefresh',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('lan_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('os', models.CharField(default='Windows 10', max_length=50)),
                ('replacement_type', models.CharField(choices=[('PC (Asset Refresh)', 'PC (Asset Refresh)'), ('Laptop (Tech Refresh)', 'Laptop (Tech Refresh)'), ('RAM (Parts Upgrade)', 'RAM (Parts Upgrade)')], max_length=100)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(limit_choices_to={'role': 'SystemEngineer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
