# Generated by Django 5.0.7 on 2025-10-27 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0009_alter_request_type_alter_techrefresh_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('lan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(default='Windows 10', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
