# Generated by Django 5.2.7 on 2025-10-29 04:51

from django.db import migrations, models  # ← tambah models sini

class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0010_engineer_alter_assignedtask_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
