# Generated by Django 5.2.7 on 2025-10-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0012_alter_request_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
