# Generated by Django 5.0.7 on 2025-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0013_alter_request_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='lan_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
