# Generated by Django 5.0.7 on 2025-10-30 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0015_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='os',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='replacement_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
