# Generated by Django 5.1.2 on 2025-11-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0017_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='old_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
