# Generated by Django 5.1.2 on 2025-11-02 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0018_assignedtask_old_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='os',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='new_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorySystem.engineer'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='lan_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='task_proofs/'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='replacement_type',
            field=models.CharField(choices=[('PC (Asset Refresh)', 'PC (Asset Refresh)'), ('Laptop (Tech Refresh)', 'Laptop (Tech Refresh)'), ('RAM (Parts Upgrade)', 'RAM (Parts Upgrade)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
