# Generated by Django 5.1.2 on 2025-11-02 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0019_remove_assignedtask_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='new_hostname',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='os',
            field=models.CharField(default='Windows 10', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='lan_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='replacement_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
