# Generated by Django 5.1.2 on 2025-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0020_remove_assignedtask_new_hostname_assignedtask_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='new_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
