# Generated by Django 5.1.2 on 2025-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystem', '0021_assignedtask_new_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
